#!/usr/bin/env python

"""
    moveit_cartesian_path.py - Version 0.1 2016-07-28

    Based on the R. Patrick Goebel's moveit_cartesian_demo.py demo code.

    Plan and execute a Cartesian path for the end-effector.

    Created for the Pi Robot Project: http://www.pirobot.org
    Copyright (c) 2014 Patrick Goebel.  All rights reserved.
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.5

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details at:

    http://www.gnu.org/licenses/gpl.html
"""

import rospy, sys, numpy as np
import moveit_commander
from copy import deepcopy
import geometry_msgs.msg
import moveit_msgs.msg

from std_msgs.msg import Header
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint

class MoveItCartesianPath:
    def __init__(self):
        rospy.init_node("moveit_cartesian_path", anonymous=False)

        rospy.loginfo("Starting node moveit_cartesian_path")

        rospy.on_shutdown(self.cleanup)

        # Initialize the move_group API
        moveit_commander.roscpp_initialize(sys.argv)

        # Initialize the move group for the ur5_arm
        self.arm = moveit_commander.MoveGroupCommander('manipulator')

        # Get the name of the end-effector link
        end_effector_link = self.arm.get_end_effector_link()

        # Set the reference frame for pose targets
        reference_frame = "/base_link"

        # Set the ur5_arm reference frame accordingly
        self.arm.set_pose_reference_frame(reference_frame)

        # Allow replanning to increase the odds of a solution
        self.arm.allow_replanning(True)

        # Allow some leeway in position (meters) and orientation (radians)
        self.arm.set_goal_position_tolerance(0.01)
        self.arm.set_goal_orientation_tolerance(0.1)

        # Get the current pose so we can add it as a waypoint
        start_pose = self.arm.get_current_pose(end_effector_link).pose

        # Initialize the waypoints list
        waypoints = []

        # Set the first waypoint to be the starting pose
        # Append the pose to the waypoints list
        wpose = deepcopy(start_pose)

        # Set the next waypoint to the right 0.5 meters


        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))

        #move_group.setMaxVelocityScalingFactor(0.01);
        #wp2
        wpose.position.x = 0.373
        wpose.position.y = 0.716
        wpose.position.z = 0.227

        wpose.orientation.x = -0.258
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.657
        waypoints.append(deepcopy(wpose))

        #move_group.setMaxVelocityScalingFactor(0.01);

        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))

        #wp3
        wpose.position.x = 0.448
        wpose.position.y = 0.581
        wpose.position.z = 0.223
        wpose.orientation.x = -0.076
        wpose.orientation.y = 0.702
        wpose.orientation.z = 0.092
	wpose.orientation.w = 0.702
        waypoints.append(deepcopy(wpose))

        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))


        #wp4
        wpose.position.x = 0.456
        wpose.position.y = 0.510
        wpose.position.z = 0.221

        wpose.orientation.x = 0.012
        wpose.orientation.y = 0.708
        wpose.orientation.z = 0.005
	wpose.orientation.w = 0.706
        waypoints.append(deepcopy(wpose))


        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))


        #wp5
        wpose.position.x = 0.443
        wpose.position.y = 0.429
        wpose.position.z = 0.219

        wpose.orientation.x = 0.109
        wpose.orientation.y = 0.701
        wpose.orientation.z = -0.093
	wpose.orientation.w = 0.698
        waypoints.append(deepcopy(wpose))

        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))


        #wp6
        wpose.position.x = 0.380
        wpose.position.y = 0.320
        wpose.position.z = 0.220

        wpose.orientation.x = 0.273
        wpose.orientation.y = 0.654
        wpose.orientation.z = -0.276
	wpose.orientation.w = 0.649
        waypoints.append(deepcopy(wpose))
        print("moved to goal 6")


        #start pose
        wpose.position.x = 0.177
        wpose.position.y = 0.527
        wpose.position.z = 0.223
        wpose.orientation.x = -0.259
        wpose.orientation.y = 0.653
        wpose.orientation.z = 0.273
	wpose.orientation.w = 0.658
        waypoints.append(deepcopy(wpose))



        if np.sqrt((wpose.position.x-start_pose.position.x)**2+(wpose.position.x-start_pose.position.x)**2 \
            +(wpose.position.x-start_pose.position.x)**2)<0.1:
            rospy.loginfo("Warnig: target position overlaps with the initial position!")

        # self.arm.set_pose_target(wpose)

        # Set the internal state to the current state
        self.arm.set_start_state_to_current_state()

        # Plan the Cartesian path connecting the waypoints

        """moveit_commander.move_group.MoveGroupCommander.compute_cartesian_path(
                self, waypoints, eef_step, jump_threshold, avoid_collisios= True)

           Compute a sequence of waypoints that make the end-effector move in straight line segments that follow the
           poses specified as waypoints. Configurations are computed for every eef_step meters;
           The jump_threshold specifies the maximum distance in configuration space between consecutive points
           in the resultingpath. The return value is a tuple: a fraction of how much of the path was followed,
           the actual RobotTrajectory.

        """
        plan, fraction = self.arm.compute_cartesian_path(waypoints, 0.01, 0.0, True)


        # plan = self.arm.plan()

        # If we have a complete plan, execute the trajectory
        if 1-fraction < 0.2:
            rospy.loginfo("Path computed successfully. Moving the arm.")
            num_pts = len(plan.joint_trajectory.points)
            rospy.loginfo("\n# intermediate waypoints = "+str(num_pts))
            self.arm.execute(plan)
            rospy.loginfo("Path execution complete.")
        else:
            rospy.loginfo("Path planning failed")

    def cleanup(self):
        rospy.loginfo("Stopping the robot")

        # Stop any current arm movement
        self.arm.stop()

        #Shut down MoveIt! cleanly
        rospy.loginfo("Shutting down Moveit!")
        moveit_commander.roscpp_shutdown()
        moveit_commander.os._exit(0)

if __name__ == "__main__":
    try:
        MoveItCartesianPath()
    except KeyboardInterrupt:
        print "Shutting down MoveItCartesianPath node."
